# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

yardstick_mcc_multiclass_impl <- function(C) {
    .Call(`_yardstick_yardstick_mcc_multiclass_impl`, C)
}

yardstick_pr_curve_binary_impl <- function(truth, estimate, thresholds) {
    .Call(`_yardstick_yardstick_pr_curve_binary_impl`, truth, estimate, thresholds)
}

