# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mcc_multiclass_cpp <- function(x) {
    .Call(`_yardstick_mcc_multiclass_cpp`, x)
}

pr_curve_cpp <- function(truth, estimate) {
    .Call(`_yardstick_pr_curve_cpp`, truth, estimate)
}

